<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.tucno.cliente.ws</groupId>
    <artifactId>cliente-ws</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>22</maven.compiler.source>
        <maven.compiler.target>22</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    
    <dependencies>
        <!--Esta dependencia sirve para que el cliente pueda consumir el servicio web de la aplicación web-->
        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>jaxws-rt</artifactId>
            <version>4.0.2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.sun.xml.ws</groupId>
                <!--Este plugin se encarga de generar las clases de cliente a partir del WSDL del servicio web-->
                <artifactId>jaxws-maven-plugin</artifactId>
                <version>4.0.2</version>
                <executions>
                    <!--execution: Define la ejecución del plugin jaxws-maven-plugin-->
                    <execution>
                        <!--goals: Define las metas que se deben cumplir en la ejecución del plugin-->
                        <goals>
                            <!--wsimport: Genera las clases de cliente a partir del WSDL del servicio web-->
                            <goal>wsimport</goal>
                        </goals>
                        <!--configuration: Define la configuración de la ejecución del plugin-->
                        <configuration>
                            <!--wsdlUrls: Define las URL de los WSDL de los servicios web a consumir-->
                            <wsdlUrls>
                                <!--URL del WSDL del servicio web a consumir-->
                                <wsdlUrl>http://localhost:8080/webapp-jaxws/ServicioWsImpl?wsdl</wsdlUrl>
                            </wsdlUrls>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>